parserOptions:
    ecmaVersion: 2017
    sourceType: module
env:
    es6: true
    node: true
extends:
    - eslint:recommended
rules:
    quotes: ['warn', 'single']
    no-useless-concat: 'error'
    prefer-template: 'error'
